version: '3'
services:
  backend:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    restart: always
    ports:
     - "6000:6000"
    
  frontend:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - "7000:7000"
